const { chromium } = require('playwright');
const path = require('path');
const D = path.join(__dirname, '../fixtures/');
const O = path.join(__dirname, '../out/');
(async () => {
  const b = await chromium.launch();
  const ctx = await b.newContext({ viewport: { width: 1366, height: 950 }, locale: 'fr-FR', timezoneId: 'Europe/Paris' });
  await ctx.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: 'http://localhost:8765' });
  const p = await ctx.newPage();
  const errors = []; p.on('pageerror', (e) => errors.push(e.message)); p.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  await p.goto('http://localhost:8765/');
  await p.fill('input[name=p1]', 'Cabinet-Test-2026!'); await p.fill('input[name=p2]', 'Cabinet-Test-2026!');
  await p.check('input[name=ack]'); await p.click('button[type=submit]'); await p.waitForSelector('.layout');
  await p.click('a[data-nav=parametres]');
  await p.fill('input[name=cabinet]', 'Cabinet Martin'); await p.fill('input[name=utilisateur]', 'Quentin');
  await p.click('form[data-form=settings] button[type=submit]');
  await p.click('main [data-action=new-client]').catch(() => {});
  await p.goto('http://localhost:8765/#/dossiers'); await p.click('main [data-action=new-client]');
  await p.fill('#modal input[name=nom]', 'ATELIER DUPONT'); await p.fill('#modal input[name=siren]', '987654321');
  await p.fill('#modal input[name=contact]', 'Monsieur Dupont'); await p.fill('#modal input[name=email]', 'contact@exemple.fr');
  await p.click('#modal button[type=submit]'); await p.waitForSelector('.grid-detail');
  await p.click('a[data-nav=fec]');
  const [ch] = await Promise.all([p.waitForEvent('filechooser'), p.click('.fec-drop')]);
  await ch.setFiles(D + '987654321FEC20251231.txt');
  await p.waitForSelector('.fec-meta');
  await p.click('button[data-action=fec-tab][data-tab=pieces]');
  await p.click('button[data-action=pieces-mode][data-mode=situation]');
  console.log('arrêté proposé (situation) :', await p.inputValue('input[data-pieces=arrete]'));
  const dump = async () => p.$$eval('.pieces-group', (g) => g.map((x) => x.querySelector('h3').textContent.replace(/\s+/g, ' ').trim() + '\n   - ' + Array.from(x.querySelectorAll('.piece span')).map((s) => s.textContent).join('\n   - ')).join('\n'));
  console.log('=== SITUATION\n' + await dump());
  await p.screenshot({ path: O + 'p1-situation.png', fullPage: true });
  await p.click('button[data-action=pieces-mode][data-mode=bilan]');
  console.log('=== BILAN (arrêté ' + await p.inputValue('input[data-pieces=arrete]') + ') : catégories ' + await p.$$eval('.pieces-group h3', (h) => h.map((x) => x.textContent.replace(/\s+/g, ' ').trim()).join(' | ')));
  console.log(await p.$$eval('.pieces-group:has(h3:text-matches("Documents de clôture|Questions")) .piece span', (s) => s.map((x) => '   - ' + x.textContent).join('\n')));
  // Retour en situation, on décoche un élément, on crée la demande
  await p.click('button[data-action=pieces-mode][data-mode=situation]');
  await p.locator('.piece input').nth(0).uncheck();
  await p.click('button[data-action=pieces-demande]');
  await p.waitForSelector('#msg-body');
  console.log('=== MAIL\nObjet : ' + await p.inputValue('#msg-subject') + '\n' + await p.inputValue('#msg-body'));
  await p.screenshot({ path: O + 'p2-mail.png' });
  await p.click('#modal [data-action=msg-copy]');
  await p.click('#modal [data-action=close-modal]');
  // La mission : on coche deux pièces reçues, puis relance
  await p.goto('http://localhost:8765/#/dossiers'); await p.click('#dossier-list a, #dossier-list tbody tr');
  await p.click('.mrow:has-text("Demande de pièces")');
  console.log('=== MISSION : ' + await p.textContent('#modal h2') + ' — statut ' + await p.$eval('#modal select[data-action-change]', (s) => s.selectedOptions[0].textContent) + ' — ' + await p.$$eval('#modal .steps li', (l) => l.length) + ' pièces');
  await p.locator('#modal input[data-action=toggle-step]').nth(0).check();
  await p.locator('#modal input[data-action=toggle-step]').nth(1).check();
  await p.click('#modal [data-action=open-msg]');
  await p.click('#modal [data-action=msg-model][data-model=relance]');
  console.log('=== RELANCE (après réception de 2 pièces)\n' + (await p.inputValue('#msg-body')).split('\n').slice(0, 12).join('\n'));
  console.log('erreurs', errors);
  await b.close();
})().catch((e) => { console.error(e); process.exit(1); });
