const { chromium } = require('playwright');
const path = require('path');
const D = path.join(__dirname, '../fixtures/');
const O = path.join(__dirname, '../out/');
(async () => {
  const b = await chromium.launch();
  const p = await (await b.newContext({ viewport: { width: 1366, height: 950 }, locale: 'fr-FR', timezoneId: 'Europe/Paris' })).newPage();
  const errors = [];
  p.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message)); p.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  await p.goto('http://localhost:8765/');
  await p.fill('input[name=p1]', 'Cabinet-Test-2026!'); await p.fill('input[name=p2]', 'Cabinet-Test-2026!');
  await p.check('input[name=ack]'); await p.click('button[type=submit]'); await p.waitForSelector('.layout');
  await p.goto('http://localhost:8765/#/fec'); await p.waitForSelector('.fec-drop');
  const [ch] = await Promise.all([p.waitForEvent('filechooser'), p.click('.fec-drop')]);
  await ch.setFiles(D + 'situ/444444444FEC20261231.txt'); await p.waitForSelector('.fec-meta');
  await p.click('button[data-tab=revue]');
  const [ch2] = await Promise.all([p.waitForEvent('filechooser'), p.click('button[data-action=fec-prev]')]);
  await ch2.setFiles(D + 'n1/444444444FEC20251231.txt');
  await p.waitForSelector('.revue-mode button.on:not([disabled])', { timeout: 30000 }); await p.waitForTimeout(500);
  console.log('mode :', (await p.textContent('.revue-mode')).replace(/\s+/g, ' ').trim());
  console.log('KPI projection :', await p.$$eval('section:has(h2:text("Projection")) .kpi', (k) => k.map((x) => x.textContent.replace(/\s+/g, ' ').trim()).join(' | ')));
  console.log('charges annuelles :', await p.$$eval('section:has(h2:text("Projection")) h3 + p + .grid-wrap tbody tr', (t) => t.map((r) => r.textContent.replace(/\s+/g, ' ').trim()).join(' / ')));
  console.log('chiffres clés (même période) :', await p.$$eval('section:has(h2:text-matches("Chiffres clés")) tbody tr', (t) => t.slice(0, 3).map((r) => r.textContent.replace(/\s+/g, ' ').trim()).join(' / ')));
  await p.screenshot({ path: O + 'situ-revue.png', fullPage: true });
  await p.click('button[data-action=prev-mode][data-mode=full]'); await p.waitForTimeout(200);
  console.log('chiffres clés (N-1 complet) :', await p.$$eval('section:has(h2:text-matches("Chiffres clés")) tbody tr', (t) => t.slice(0, 3).map((r) => r.textContent.replace(/\s+/g, ' ').trim()).join(' / ')));
  await p.click('button[data-tab=ecritures]'); await p.waitForTimeout(200);
  console.log('date écritures :', await p.$eval('input[data-ecr=date]', (i) => i.value));
  console.log('propositions situation :', await p.$$eval('section:has(h2:text-matches("Situation")) .ecr-prop', (l) => l.map((x) => x.querySelector('strong').textContent + ' :: ' + Array.from(x.querySelectorAll('.ecr-lines tbody tr')).map((r) => r.textContent.replace(/\s+/g, ' ').trim()).join(' / ')).join('\n  ')));
  console.log('erreurs', errors);
  await b.close();
})();
